### ISSUE TITLE
How to check accuracy on binary classification problems with {-1, +1} labels?

### ISSUE THREAD

**Issue by nstiurca** [pluskid/Mocha.jl#134]
This "issue" isn't necessarily a bug or feature request, but rather I'm abusing the issue tracking in lieu of a proper discussion thread since Github doesn't seem to have anything of the sort.

I submitted the HingeLossLayer earlier this week, and I need to check the accuracy as I train. The simplest thing would be if I could just use the existing AccuracyLayer, but I'm not sure what I'm supposed to give it as inputs. My labels are from the set {-1, +1}, and computing the hinge loss is a bit different from computing final prediction and correct/incorrect classification. For example, if my output layer outputs +0.25, and the label is +1, then the hinge loss is 0.75, but accuracy-wise this is a correct prediction because the sign is correct.

To get proper accuracy statistics for my use case, I can think of three possibilities, and I would like some feedback on how to proceed.

 1. Write a new layer, say BinaryAccuracyLayer which expects labels from {-1, +1}, and checks only the signs of the prediction.
 2. Modify the HingeLossLayer to accumulate accuracy statistics on top of the loss statistics it already accumulates. This might slow down the training a bit, but probably very little compared to how much work is done in ConvolutionLayers and InnerProductLayers.
 3. Somehow leverage the existing AccuracyLayer, maybe by somehow transforming the values of the prediction layer and the labels. I'm not sure what this would look like, however.

**Comment by pluskid** [comment]
The existing accuracy layer is really designed to handle multi-class classification case. In that case, when you have K classes, the output will be K numbers, and you take the argmax. However, for binary classifications, your output is 1 number (instead of 2). So it is going to be messy if you make the current `AccuracyLayer` to handle both binary classification and multi-class classification.

I +1 the idea of making a new `BinaryAccuracyLayer`. Please state explicitly in the documentation that the expected labels are {-1,+1}, just to avoid confusing with {0,1}. People might get confused because there is really no standard way of specifying this. Thanks!

**Comment by nstiurca** [comment]
Ok, I will try to crank out a `BinaryAccuracyLayer` this weekend. What do you think about allowing the user to set a threshold, eg 0 for {-1, +1} labels, or 0.5 for {0, 1} labels?

**Comment by nstiurca** [comment]
By the way, for multi-class labels, are the labels expected to be {0, 1, ..., N-1}, or {1, 2, ..., N}?

**Comment by pluskid** [comment]
@nstiurca Yes I think it is sensible to allow a user specified threshold so you can handle both {-1,+1} case and {0,1} case, though I guess the loss layer only works with {-1,+1} case.

The multiclass labels are suppose to be {0,1,...,N-1}
