### ISSUE TITLE
ImageNet notebook fix

### ISSUE THREAD

**Issue by ViralBShah** [pluskid/Mocha.jl#143]
I was trying to run the ImageNet notebook demo, and found that I had to comment out line 96 in `tools/image-classifier.jl` to get the classifier to work.
```
#      image = convert(Image{RGB}, image)                                       
```

**Comment by pluskid** [comment]
Thanks for reporting this! It seems Images.jl has changed a lot that the code does not work any more. Commenting out that line let the code go through, but the prediction is incorrect. So I guess I need to replace that step with something else.

I will leave this issue open until I find some time to investigate this further. Thanks again for reporting!

**Comment by ViralBShah** [comment]
I wondered about that. At least the demo goes through fine and even with this, it detects a few elephants from wikipedia and google images. Would love to have the right version.

**Comment by pluskid** [comment]
@ViralBShah My guess is that because we are not using the correct conversion, so the bytes we get from the image is not in the correct format, and the classifier gets confused. It might be that the expected numbers are within range of [0,1] but we actually get [0,255] (or the other way around). Then when we subtract the mean, it will screw up everything. I need to check Images.jl to find out the new correct way of getting the right values.

**Comment by pluskid** [comment]
@ViralBShah Actually now I tried again (after updating `Images.jl` and `Colors.jl`), the original code works without any conversion error. And the classification is correct.

**Comment by pluskid** [comment]
I'm closing this issue. Feel free to re-open it if needed.

**Comment by ViralBShah** [comment]
Yes, I will reopen it if required. It doesn't work for me, but let me start from a clean 0.4 environment.
