### ISSUE TITLE
Statistics for SquareLossLayer

### ISSUE THREAD

**Issue by michael-p** [pluskid/Mocha.jl#43]
Is there a way to test a net during training using the ValidationPerformance-coffeebreak when doing regression with a final SquareLossLayer? It seems to me that only the AccuracyLayer generates statistics but I think this would also be very useful for the SquareLossLayer. Am I missing something or is this just not yet implemented?

Thanks a lot! Mocha is a really great tool!

**Comment by pluskid** [comment]
@michael-p it is simply not implemented yet. I think it will be easy to add, square loss layer could be both a loss layer and a stat layer. While I could add this, There may be about one week delay as  I'm currently traveling. You are also welcome to add this and send us a pull request!

**Comment by michael-p** [comment]
No problem, thank you very much for your great work on Mocha! Julia+Mocha is really a pleasure to work with compared to all other DL tools I worked with before.

**Comment by MarkusQ** [comment]
I came here to open a ticket on exactly this issue (and validate the assumption that I wasn't missing something obvious).

Encouraged by the comments here I'm going to play a bit with implementing stats on SquareLossLayer myself over the next day or so; if I get anywhere I'll submit a pull request & note it here.  If not...I'd like to second the request for this feature.  :)

Hope your travels are going well, and thanks for all your work on Mocha!

**Comment by pluskid** [comment]
@michael-p @MarkusQ I have just pushed some changes to the master which makes SquareLossLayer also a statistics layer like accuracy layer. It should work out-of-the-box but I have not test it very carefully as I do not have a regression problem at hand. But maybe you might be interested to try to see if this satisfies the needs.

**Comment by MarkusQ** [comment]
Thanks!

I'll play with it some today and let you know.

**Comment by MarkusQ** [comment]
Looking at your changes, it looks very similar to what I'd been playing with last night in attempting to implement this.  The main difference seems to be in the projection of loss onto accuracy.  I was thinking I needed to take the square root of the loss renormalized to [0,1) as the accuracy, where you're using the loss directly.  Secondarily, I was dithering between weighing the accuracy by the number of components and decided not to, instead treating the dot product as a single observation.  That left me with:

    state.accuracy = float64(state.accuracy * state.n_accum + sqrt(2*state.loss)) / (state.n_accum + 1)
    state.n_accum += 1

Are there any pros/cons to either method, or is it mostly a matter of taste?

**Comment by pluskid** [comment]
@MarkusQ I think it is more a matter of taste. In principle one could define any formula for a *statistics* as long as it makes sense to you (and your problem). I'm using this formula because it is consistent with the square loss itself, which is defined as

L = 0.5*1/N * (||y1 - pred1||^2 + ... + ||yN - predN||^2)

**Comment by MarkusQ** [comment]
So yeah, the sense of the stats is opposite from the accuracy layer (0.0% is perfect, as opposed to 100.0% with an accuracy layer) and the scaling is non-linear (if the target is [1.0] and the network learns [0.5] the stat-output of SquareLoss is 1/8 instead of 1/2 as I was expecting) but it's certainly usable once you understand what you're seeing.  And having it consistent with the SquareLoss is as reasonable as having it consistent with the Accuracy.

I'm happy with it as is if you & @michael-p are.

Thanks!

**Comment by michael-p** [comment]
Exactly what I needed! Thank you very much!
