### ISSUE TITLE
It is not clear from documentation if AsyncHDF5DataLayer shuffles automatically

### ISSUE THREAD

**Issue by bisraelsen** [pluskid/Mocha.jl#61]
I am pretty sure that AsyncHDF5DataLayer does not shuffle automatically. Is this true?

**Comment by pluskid** [comment]
No it does **not** shuffle the data by default. I should document it more clearly, but all the properties of `AsyncHDF5DataLayer` are the same (for the user) to `HDF5DataLayer` and the `shuffle` property is `false` by default in the doc for `HDF5DataLayer`. This is chosen as the default behavior because I do not want unexpected behavior unless the user explicitly choose to shuffle. For example, if users want to use the net to extract some features, then shuffling should not be used.

**Comment by bisraelsen** [comment]
I thought that might be the case but couldn't be sure.

Thanks for the reply. I appreciate it.
