### ISSUE TITLE
How make prediction?

### ISSUE THREAD

**Issue by chapaev28** [pluskid/Mocha.jl#80]
Hi guys. I'm newbie in julia and mocha. I use examples and train my model. but in my task i have multiple output. for example in input image 32 x 32 on output image 12 x 12. training is ok. but i dont know how i may use my net. i load snapshot of trained model...but what i need to do next? in caffe i use method forward(forward_all). how i can froward my image through net? 

Thanks.

**Comment by pluskid** [comment]
@chapaev28 There is a similar function in Mocha. Basically, you can call `forward`, which runs one mini-batch only. Or you can call `forward_epoch` which runs one whole epoch (1 round over all the data). Typically, you do not want to run this on the original network used for training, because that is based on a data layer for the training set. So you can create another network, but with a new data layer (either hdf5-data or memory data, depending on your input), and do something like this:

```julia
  data_layer = HDF5DataLayer(source="data/test.txt", batch_size=128, shuffle=false)
  acc_layer = AccuracyLayer(bottoms=[:pred, :label])
  net = Net("TIMIT-DNN-Test", backend, [data_layer, common_layers..., pred_layer, acc_layer])
  load_snapshot(net, basedir)
  init(net)

  forward_epoch(net)
```

Note here `common_layers` and `pred_layer` are the same layers you used to construct the training net. `load_snapshot` will load from a snapshot you saved during training. The code in [this tutorial](http://mochajl.readthedocs.org/en/latest/tutorial/ijulia-imagenet.html) contains a shallow wrapper (the `Classifier`) to do prediction based on images.
